#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt update -y
apt install haproxy -y

# Distribute requests using a roundrobin algorithm
echo "frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server  3328-web-01 35.237.22.35 check
    server  3328-web-02 35.237.118.104 check" > /etc/haproxy/haproxy.cfg

service haproxy start
