#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation
# from listening on port 80, fix short and sweet

cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
